
//USER
const USER_ACCOUNT = "USER_ACCOUNT";
const USER_PASSWORD = "USER_PASSWORD";
const USER_NICKNAME = "USER_NICKNAME";
const USER_AVATAR = "USER_AVATAR";
const USER_BIO = "USER_BIO";


//ARTICLE
const ARTICLE_TITLE = "ARTICLE_TITLE";
const ARTICLE_SUMMARY = "ARTICLE_SUMMARY";
const ARTICLE_CONTENT = "ARTICLE_CONTENT";
const ARTICLE_VIEWNUM = "ARTICLE_VIEWNUM";
const ARTICLE_COMMENTNUM = "ARTICLE_COMMENTNUM";

//COMMENT
const COMMENT_COMMENT = "COMMENT_COMMENT";

export{
  USER_ACCOUNT,
  USER_PASSWORD,
  USER_NICKNAME,
  USER_AVATAR,
  USER_BIO,

  ARTICLE_TITLE,
  ARTICLE_SUMMARY,
  ARTICLE_CONTENT,
  ARTICLE_VIEWNUM,
  ARTICLE_COMMENTNUM,

  COMMENT_COMMENT
}