//USER
const USER_ACCOUNT = "USER_ACCOUNT";
const USER_PASSWORD = "USER_PASSWORD";
const USER_NICKNAME = "USER_NICKNAME";
const USER_AVATAR = "USER_AVATAR";
const USER_BIO = "USER_BIO";
const SET_MESSAGE = "SET_MESSAGE";
const SIGN_UP = "SIGN_UP";
const SIGN_IN = "SIGN_IN";
const TOKEN = "TOKEN"

//ARTICLE
const ARTICLE_TITLE = "ARTICLE_TITLE";
const ARTICLE_SUMMARY = "ARTICLE_SUMMARY";
const ARTICLE_CONTENT = "ARTICLE_CONTENT";
const ARTICLE_VIEWNUM = "ARTICLE_VIEWNUM";
const ARTICLE_COMMENTNUM = "ARTICLE_COMMENTNUM";
const UPLOAD_ARTICLE = "UPLOAD_ARTICLE";
const ARTICLE = "ARTICLE";

//COMMENT
const COMMENT_COMMENT = "COMMENT_COMMENT";

export {
  USER_ACCOUNT,
  USER_PASSWORD,
  USER_NICKNAME,
  USER_AVATAR,
  USER_BIO,

  SIGN_UP,
  SIGN_IN,
  SET_MESSAGE,
  TOKEN,
  
  //article
  ARTICLE_TITLE,
  ARTICLE_SUMMARY,
  ARTICLE_CONTENT,
  ARTICLE_VIEWNUM,
  ARTICLE_COMMENTNUM,
  UPLOAD_ARTICLE,
  ARTICLE,
  
  //comment
  COMMENT_COMMENT
};
